baseURL = ""
paginate =  100
defaultContentLanguage = "en"
enableEmoji = true
footnotereturnlinkcontents = "↩"
languageCode = "en-us"
metaDataFormat = "yaml"
title = "Fabula"
googleAnalytics = ""
pluralizeListTitles = false

[social]
facebook = ""
twitter = ""
email = ""
phone = ""

[params]
description = "Skeleton of a Hugo theme."

[[menu.global]]
name = "News"
weight = 1
identifier = "news"
url = "/news/"